- name: Playbook for configure ELK cluster
  hosts: "{{ remote_hosts }}"
  strategy: linear
  remote_user: ansible
  become: yes
  become_method: sudo

  vars:


  tasks:
    - name: Copy file etc/hosts to all servers on elk_cluster
      copy: src=/etc/ansible/inventory/vars/elk_cluster/hosts.j2 dst=/etc/hosts
