- name: Playbook for configure elastic
  hosts: "{{ remote_hosts }}"
  strategy: linear
  remote_user: ansible
  become: yes
  become_method: sudo

  vars:


  tasks:
    - name: Define elastic1 private IP
      shell: "ifconfig -a | grep broadcast | awk '{print $2}'"
      register: elastic1_ip
      when: ansible_hostname == "elastic1"

    - name: Define elastic2 private IP
      shell: "ifconfig -a | grep broadcast | awk '{print $2}'"
      register: elastic2_ip
      when: ansible_hostname == "elastic2"

    - name: Define elastic3 private IP
      shell: "ifconfig -a | grep broadcast | awk '{print $2}'"
      register: elastic3_ip
      when: ansible_hostname == "elastic3"

    - name: Define elastic2 private IP
      shell: "ifconfig -a | grep broadcast | awk '{print $2}'"
      register: elastic2_ip
      when: ansible_hostname == "elastic2"

    - name: Define elastic3 private IP
      shell: "ifconfig -a | grep broadcast | awk '{print $2}'"
      register: elastic3_ip
      when: ansible_hostname == "elastic3"

    - name: install Elasticsearch
      yum: name=elasticsearch state=present

    - name: define configuration files for elastic1
      copy: src=/etc/ansible/inventory/vars/elk_cluster/elastic/elastic1.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
      when: ansible_hostname == "elastic1"

    - name: define configuration files for elastic2
      copy: src=/etc/ansible/inventory/vars/elk_cluster/elastic/elastic2.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
      when: ansible_hostname == "elastic2"

    - name: define configuration files for elastic3
      copy: src=/etc/ansible/inventory/vars/elk_cluster/elastic/elastic3.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
      when: ansible_hostname == "elastic3"

    - name: Define elastic1 IP
      shell: "sed -i 's/elastic1_ip/{{elastic1.stdout}}/g' /etc/elasticsearch/elasticsearch.yml"

    - name: Define elastic2 IP
      shell: "sed -i 's/elastic2_ip/{{elastic2.stdout}}/g' /etc/elasticsearch/elasticsearch.yml"

    - name: Define elastic3 IP
      shell: "sed -i 's/elastic3_ip/{{elastic3.stdout}}/g' /etc/elasticsearch/elasticsearch.yml"

    - name: change parameter Xms in jvm option
      shell: "sed -i 's/-Xms1g/-Xms512m/g' /etc/elasticsearch/jvm.options"

    - name: change parameter Xmx in jvm option
      shell: "sed -i 's/-Xmx1g/-Xmx512m/g' /etc/elasticsearch/jvm.options"

    - name: start elasticsearch
      service: name=elasticsearch state=started enabled=yes
