- name: Playbook for configure logstash
  hosts: "{{ remote_hosts }}"
  strategy: linear
  remote_user: ansible
  become: yes
  become_method: sudo

  vars:


  tasks:
    - name: Install logstash
      yum: name=logstash state=present

    - name: Copy files to dest servers
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
          - { src: '/etc/ansible/inventory/vars/elk_cluster/logstash/02-beats-input.conf.j2', dest: '/etc/logstash/conf.d/02-beats-input.conf.j2' }
          - { src: '/etc/ansible/inventory/vars/elk_cluster/logstash/10-syslog-filter.conf.j2', dest: '/etc/logstash/conf.d/10-syslog-filter.conf' }
          - { src: '/etc/ansible/inventory/vars/elk_cluster/logstash/30-elasticsearch-output.conf.j2', dest: '/etc/logstash/conf.d/30-elasticsearch-output.conf' }

    - name: Start Logstash
      service: name=logstash state=started enabled=yes
