- name: Playbook for configure kibana
  hosts: "{{ remote_hosts }}"
  strategy: linear
  remote_user: ansible
  become: yes
  become_method: sudo

  vars:


  tasks:
    - name: install EPEL repo
      shell: "amazon-linux-extras install epel -y"

    - name: install kibana and nginx
      yum: name={{ item }} state=present
      with_items:
        - kibana
        - nginx
        - certbot
        - python2-certbot-nginx

    - name: configure NGINX
      copy: src=/etc/ansible/inventory/vars/elk_cluster/kibana/nginx_default.conf dest=/etc/nginx/conf.d/default.conf

    - name: Copy Configure Certbot
      copy: src=/etc/ansible/inventory/vars/elk_cluster/kibana/le.tar dest=/etc/letsencrypt/le.tar

    - name: Decompress conf files
      shell: "tar -xf /etc/letsencrypt/le.tar"

    - name: Install oauth2
      copy: src=/etc/ansible/inventory/vars/elk_cluster/kibana/oauth2_proxy  dest=/sbin/oauth2_proxy

    - name: Configure oauth2
      copy: src=/etc/ansible/inventory/vars/elk_cluster/kibana/oauth_proxy.cfg  dest=/etc/oauth2_proxy.cfg

    - name: Define oauth2 as service
      copy: src=/etc/ansible/inventory/vars/elk_cluster/kibana/oauth2.service  dest=/etc/systemd/system/oauth2.service

    - name: Reload systemctl daemon
      shell: "systemctl daemon-reload"

    - name: Start oauth2 service
      service: name=oauth2 state=started enabled=yes
